// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240803160357_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 100m,
                            Title = "Devlet"
                        },
                        new
                        {
                            Id = 2,
                            Price = 200m,
                            Title = "Sefiller"
                        },
                        new
                        {
                            Id = 3,
                            Price = 150m,
                            Title = "Suç ve Ceza"
                        },
                        new
                        {
                            Id = 4,
                            Price = 120m,
                            Title = "Beyaz Zambaklar Ülkesinde"
                        },
                        new
                        {
                            Id = 5,
                            Price = 180m,
                            Title = "İnce Memed"
                        },
                        new
                        {
                            Id = 6,
                            Price = 110m,
                            Title = "İstanbul Hatırası"
                        },
                        new
                        {
                            Id = 7,
                            Price = 90m,
                            Title = "Kuyucaklı Yusuf"
                        },
                        new
                        {
                            Id = 8,
                            Price = 110m,
                            Title = "Kürk Mantolu Madonna"
                        },
                        new
                        {
                            Id = 9,
                            Price = 90m,
                            Title = "Alıştırmalarla SQL"
                        },
                        new
                        {
                            Id = 10,
                            Price = 50m,
                            Title = "Prens"
                        },
                        new
                        {
                            Id = 11,
                            Price = 33m,
                            Title = "Dönüşüm"
                        },
                        new
                        {
                            Id = 12,
                            Price = 21m,
                            Title = "Karamazov Kardeşler"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
